#!/usr/bin/env python3
"""Generate the immutable qwen-ref-v2 nonlinear lookup tables.

This tool is not used by inference.  It deliberately uses Decimal at high
precision, then rounds each table entry once to IEEE-754 binary32.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
from decimal import Decimal, ROUND_FLOOR, localcontext
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "qwen_ref" / "fp_tables.py"
DEFAULT_MANIFEST = ROOT / "spec" / "arithmetic" / "qwen-ref-v2" / "tables-manifest.json"
PRECISION = 110
EXP_STEP = Decimal(1) / 256
RSQRT_STEP = Decimal(1) / 256
PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944"
    "5923078164062862089986280348253421170679"
)


def round_ratio_pow2(numerator: int, denominator: int, shift: int) -> int:
    if shift >= 0:
        numerator <<= shift
    else:
        denominator <<= -shift
    quotient, remainder = divmod(numerator, denominator)
    doubled = remainder << 1
    if doubled > denominator or (doubled == denominator and quotient & 1):
        quotient += 1
    return quotient


def f32_bits(value: Decimal) -> int:
    """Round a finite Decimal directly to binary32 RNE (no binary64 hop)."""
    sign = 0x8000_0000 if value.is_signed() else 0
    numerator, denominator = abs(value).as_integer_ratio()
    if not numerator:
        return sign
    exponent = numerator.bit_length() - denominator.bit_length()
    if exponent >= 0:
        if numerator < denominator << exponent:
            exponent -= 1
    elif numerator << -exponent < denominator:
        exponent -= 1
    if exponent >= -126:
        significand = round_ratio_pow2(
            numerator, denominator, 23 - exponent
        )
        if significand == 0x0100_0000:
            significand >>= 1
            exponent += 1
        return sign | ((exponent + 127) << 23) | (significand & 0x007F_FFFF)
    fraction = round_ratio_pow2(numerator, denominator, 149)
    if fraction == 0x0080_0000:
        return sign | 0x0080_0000
    return sign | fraction


def decimal_sin_cos(angle: Decimal) -> tuple[Decimal, Decimal]:
    """Evaluate sin/cos without using the platform math library."""
    two_pi = PI * 2
    angle -= (angle / two_pi).to_integral_value(rounding=ROUND_FLOOR) * two_pi
    if angle > PI:
        angle -= two_pi
    square = angle * angle
    sine = sine_term = angle
    cosine = cosine_term = Decimal(1)
    tolerance = Decimal(10) ** (-(PRECISION - 8))
    n = 1
    while True:
        sine_term *= -square / Decimal((2 * n) * (2 * n + 1))
        cosine_term *= -square / Decimal((2 * n - 1) * (2 * n))
        sine += sine_term
        cosine += cosine_term
        if abs(sine_term) < tolerance and abs(cosine_term) < tolerance:
            return sine, cosine
        n += 1


def words_digest(words: list[int]) -> str:
    payload = b"".join(struct.pack("<I", word) for word in words)
    return hashlib.sha256(payload).hexdigest()


def format_words(name: str, words: list[int]) -> str:
    lines = [f"{name} = ("]
    for offset in range(0, len(words), 8):
        row = ", ".join(f"0x{word:08x}" for word in words[offset:offset + 8])
        lines.append(f"    {row},")
    lines.append(")")
    return "\n".join(lines)


def generate_words() -> tuple[list[int], list[int], list[int]]:
    with localcontext() as context:
        context.prec = PRECISION
        exp_words = [
            f32_bits((-Decimal(index) * EXP_STEP).exp())
            for index in range(16 * 256 + 1)
        ]
        rsqrt_words = [
            f32_bits(Decimal(1) / (Decimal(1) + index * RSQRT_STEP).sqrt())
            for index in range(3 * 256 + 1)
        ]
        rope_words: list[int] = []
        theta = Decimal(1_000_000)
        for position in range(128):
            for index in range(64):
                exponent = Decimal(2 * index) / Decimal(128)
                frequency = (-(theta.ln() * exponent)).exp()
                sine, cosine = decimal_sin_cos(Decimal(position) * frequency)
                rope_words.extend((f32_bits(cosine), f32_bits(sine)))
    return exp_words, rsqrt_words, rope_words


def render_module(
    exp_words: list[int], rsqrt_words: list[int], rope_words: list[int]
) -> str:
    return f'''"""Generated qwen-ref-v2 lookup ROMs; do not edit by hand.

Generated by spec/arithmetic/generate_qwen_ref_v2_tables.py. Values are
IEEE-754 binary32 bit patterns. Integrity metadata has one authority:
spec/arithmetic/qwen-ref-v2/tables-manifest.json.
"""

EXP_STEP_LOG2 = -8
EXP_MIN = -16
RSQRT_STEP_LOG2 = -8
ROPE_POSITIONS = 128
ROPE_PAIRS = 64

{format_words("EXP_NEG_F32_BITS", exp_words)}

{format_words("RSQRT_F32_BITS", rsqrt_words)}

{format_words("ROPE_COS_SIN_F32_BITS", rope_words)}
'''


def render_manifest(
    exp_words: list[int], rsqrt_words: list[int], rope_words: list[int]
) -> str:
    all_words = exp_words + rsqrt_words + rope_words
    document = {
        "schema": "qwen-ref-table-manifest-v1",
        "arithmetic_profile": "qwen-ref-v2",
        "word_encoding": "little-endian-ieee754-binary32",
        "combined_order": ["exp_negative", "reciprocal_sqrt", "rope_cos_sin"],
        "combined_sha256": words_digest(all_words),
        "tables": {
            "exp_negative": {
                "python_symbol": "EXP_NEG_F32_BITS",
                "words": len(exp_words),
                "sha256": words_digest(exp_words),
                "address": "i=-256*x, i=0..4096",
            },
            "reciprocal_sqrt": {
                "python_symbol": "RSQRT_F32_BITS",
                "words": len(rsqrt_words),
                "sha256": words_digest(rsqrt_words),
                "address": "i=256*(normalized_x-1), i=0..768",
            },
            "rope_cos_sin": {
                "python_symbol": "ROPE_COS_SIN_F32_BITS",
                "words": len(rope_words),
                "sha256": words_digest(rope_words),
                "address": "((position*64+pair)*2)+component; cos=0,sin=1",
            },
        },
    }
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    parser.add_argument("--manifest-output", type=Path)
    arguments = parser.parse_args()
    output = arguments.output or DEFAULT_OUTPUT
    if arguments.manifest_output:
        manifest_output = arguments.manifest_output
    elif arguments.output:
        manifest_output = output.with_suffix(output.suffix + ".manifest.json")
    else:
        manifest_output = DEFAULT_MANIFEST

    exp_words, rsqrt_words, rope_words = generate_words()
    output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_module(exp_words, rsqrt_words, rope_words), encoding="ascii")
    manifest_output.write_text(
        render_manifest(exp_words, rsqrt_words, rope_words), encoding="ascii"
    )
    print(f"wrote {output}")
    print(f"wrote {manifest_output}")


if __name__ == "__main__":
    main()
